# Generated by Django 3.2.7 on 2021-09-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cte_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('code_kphz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CTE_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cte_product_id', models.BigIntegerField()),
                ('value', models.CharField(max_length=255)),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cte')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('public_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('сustomer_inn', models.IntegerField()),
                ('сustomer_kpp', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('supplier_inn', models.IntegerField()),
                ('supplier_kpp', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cte')),
            ],
        ),
    ]
