# Generated by Django 3.2.7 on 2021-09-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte_product',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='cte_product',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
