# Generated by Django 3.2.7 on 2021-09-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210924_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte_product',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
