# Generated by Django 3.2.7 on 2021-09-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cte_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte',
            name='category',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='cte',
            name='code_kphz',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='cte',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
