# Generated by Django 3.2.7 on 2021-09-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210925_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte',
            name='category',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='code_kphz',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='cte_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cte_product',
            name='cte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cte'),
        ),
        migrations.AlterField(
            model_name='cte_product',
            name='cte_product_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
