# Generated by Django 3.2.7 on 2021-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210925_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte',
            name='category',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='code_kphz',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='name',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
