# Generated by Django 3.2.7 on 2021-09-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210925_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cte_product',
            name='cte',
        ),
        migrations.AddField(
            model_name='cte',
            name='cte_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cte_product'),
        ),
    ]
