# Generated by Django 3.2.7 on 2021-09-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210925_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='public_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier_inn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier_kpp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='сustomer_inn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='сustomer_kpp',
            field=models.BigIntegerField(null=True),
        ),
    ]
