# Generated by Django 3.2.7 on 2021-09-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210925_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cte',
            name='contract',
        ),
        migrations.AddField(
            model_name='cte',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.contract'),
        ),
    ]
