# Generated by Django 3.2.7 on 2021-09-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210925_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.contract'),
        ),
    ]
