# Generated by Django 3.2.7 on 2021-09-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cte_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contract'),
        ),
    ]
