# Generated by Django 3.2.7 on 2021-09-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210925_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cte',
            name='contract',
        ),
        migrations.AddField(
            model_name='cte',
            name='contract_cte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractcte'),
        ),
        migrations.AlterField(
            model_name='cte_product',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cte'),
        ),
    ]
