# Generated by Django 3.2.7 on 2021-09-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210925_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='number',
        ),
    ]
